define("discourse/plugins/discourse-solved/discourse/components/solved-accept-answer-button",["exports","@glimmer/component","@ember/object","@ember/service","discourse/components/d-button","discourse/lib/ajax","discourse/lib/ajax-error","@ember/component","@ember/template-factory"],(function(e,t,s,o,n,c,i,r,a){"use strict"
Object.defineProperty(e,"__esModule",{value:!0}),e.default=void 0
class d extends t.default{static hidden(e){return e.post.topic_accepted_answer}static#e=(()=>dt7948.g(this.prototype,"appEvents",[o.service]))()
#t=(()=>{dt7948.i(this,"appEvents")})()
static#s=(()=>dt7948.g(this.prototype,"currentUser",[o.service]))()
#o=(()=>{dt7948.i(this,"currentUser")})()
get showLabel(){return this.currentUser?.id===this.args.post.topicCreatedById}acceptAnswer(){const e=this.args.post;(function(e,t){const s=e.topic;(function(e){const t=e.get("postStream.posts")
t.forEach((e=>{e.get("post_number")>1&&e.setProperties({accepted_answer:!1,can_accept_answer:!0,can_unaccept_answer:!1,topic_accepted_answer:!1})}))})(s),e.setProperties({can_unaccept_answer:!0,can_accept_answer:!1,accepted_answer:!0}),s.set("accepted_answer",{username:e.username,name:e.name,post_number:e.post_number,excerpt:e.cooked,accepter_username:t.username,accepter_name:t.name}),(0,c.ajax)("/solution/accept",{type:"POST",data:{id:e.id}}).catch(i.popupAjaxError)})(e,this.currentUser),this.appEvents.trigger("discourse-solved:solution-toggled",e),e.get("topic.postStream.posts").forEach((e=>{e.set("topic_accepted_answer",!0),this.appEvents.trigger("post-stream:refresh",{id:e.id})}))}static#n=(()=>dt7948.n(this.prototype,"acceptAnswer",[s.action]))()
static#c=(()=>(0,r.setComponentTemplate)((0,a.createTemplateFactory)({id:"XyW91b1h",block:'[[[1,"\\n    "],[8,[32,0],[[24,0,"post-action-menu__solved-unaccepted unaccepted"],[17,1]],[["@action","@icon","@label","@title"],[[30,0,["acceptAnswer"]],"far-square-check",[52,[30,0,["showLabel"]],"solved.solution"],"solved.accept_answer"]],null],[1,"\\n  "]],["&attrs"],false,["if"]]',moduleName:"/var/www/discourse/app/assets/javascripts/discourse/discourse/plugins/discourse-solved/discourse/components/solved-accept-answer-button.js",scope:()=>[n.default],isStrictMode:!0}),this))()}e.default=d})),define("discourse/plugins/discourse-solved/discourse/components/solved-accepted-answer",["exports","@glimmer/component","@glimmer/tracking","@ember/modifier","@ember/object","@ember/service","@ember/template","discourse/components/async-content","discourse/components/post/cooked-html","discourse/helpers/concat-class","discourse/helpers/d-icon","discourse/lib/ajax","discourse/lib/icon-library","discourse/lib/utilities","discourse-i18n","@ember/component","@ember/template-factory"],(function(e,t,s,o,n,c,i,r,a,d,l,u,p,m,v,_,f){"use strict"
Object.defineProperty(e,"__esModule",{value:!0}),e.default=void 0
class g extends t.default{static#e=(()=>dt7948.g(this.prototype,"siteSettings",[c.service]))()
#i=(()=>{dt7948.i(this,"siteSettings")})()
static#s=(()=>dt7948.g(this.prototype,"store",[c.service]))()
#r=(()=>{dt7948.i(this,"store")})()
static#n=(()=>dt7948.g(this.prototype,"expanded",[s.tracked],(function(){return!1})))()
#a=(()=>{dt7948.i(this,"expanded")})()
get acceptedAnswer(){return this.topic.accepted_answer}get quoteId(){return`accepted-answer-${this.topic.id}-${this.acceptedAnswer.post_number}`}get topic(){return this.args.post.topic}get hasExcerpt(){return!!this.acceptedAnswer.excerpt}get htmlAccepter(){const e=this.acceptedAnswer.accepter_username,t=this.acceptedAnswer.accepter_name
if(!this.siteSettings.show_who_marked_solved)return
const s=this.siteSettings.display_name_on_posts&&t?t:(0,m.formatUsername)(e)
return(0,i.htmlSafe)((0,v.i18n)("solved.marked_solved_by",{username:s,username_lower:e.toLowerCase()}))}get htmlSolvedBy(){const e=this.acceptedAnswer.username,t=this.acceptedAnswer.name,s=this.acceptedAnswer.post_number
if(!e||!s)return
const o=this.siteSettings.display_name_on_posts&&t?t:(0,m.formatUsername)(e),n={icon:(0,p.iconHTML)("square-check",{class:"accepted"}),username_lower:e.toLowerCase(),username:o,post_path:`${this.topic.url}/${s}`,post_number:s,user_path:this.store.createRecord("user",{username:e}).path}
return(0,i.htmlSafe)((0,v.i18n)("solved.accepted_html",n))}toggleExpandedPost(){this.hasExcerpt&&(this.expanded=!this.expanded)}static#c=(()=>dt7948.n(this.prototype,"toggleExpandedPost",[n.action]))()
async loadExpandedAcceptedAnswer(e){const t=await(0,u.ajax)(`/posts/by_number/${this.topic.id}/${e}`)
return this.store.createRecord("post",t)}static#d=(()=>dt7948.n(this.prototype,"loadExpandedAcceptedAnswer",[n.action]))()
static#l=(()=>(0,_.setComponentTemplate)((0,f.createTemplateFactory)({id:"ctsHlk+u",block:'[[[1,"\\n    "],[10,"aside"],[14,0,"quote accepted-answer"],[15,"data-post",[30,0,["acceptedAnswer","post_number"]]],[15,"data-topic",[30,0,["topic","id"]]],[15,"data-expanded",[30,0,["expanded"]]],[12],[1,"\\n"],[1,"      "],[11,0],[16,0,[28,[32,0],["title",[52,[51,[30,0,["hasExcerpt"]]],"title-only"],[52,[30,0,["hasExcerpt"]],"quote__title--can-toggle-content"]],null]],[4,[32,1],["click",[30,0,["toggleExpandedPost"]]],null],[12],[1,"\\n        "],[10,0],[14,0,"accepted-answer--solver-accepter"],[12],[1,"\\n          "],[10,0],[14,0,"accepted-answer--solver"],[12],[1,"\\n            "],[1,[30,0,["htmlSolvedBy"]]],[1,"\\n          "],[13],[1,"\\n          "],[10,0],[14,0,"accepted-answer--accepter"],[12],[1,"\\n            "],[1,[30,0,["htmlAccepter"]]],[1,"\\n          "],[13],[1,"\\n        "],[13],[1,"\\n"],[41,[30,0,["hasExcerpt"]],[[[1,"          "],[10,0],[14,0,"quote-controls"],[12],[1,"\\n            "],[10,"button"],[15,"aria-controls",[30,0,["quoteId"]]],[15,"aria-expanded",[30,0,["expanded"]]],[14,0,"quote-toggle btn-flat"],[14,4,"button"],[12],[1,"\\n              "],[1,[28,[32,2],[[52,[30,0,["expanded"]],"chevron-up","chevron-down"]],[["title"],["post.expand_collapse"]]]],[1,"\\n            "],[13],[1,"\\n          "],[13],[1,"\\n"]],[]],null],[1,"      "],[13],[1,"\\n"],[41,[30,0,["hasExcerpt"]],[[[1,"        "],[10,"blockquote"],[15,1,[30,0,["quoteId"]]],[12],[1,"\\n"],[41,[30,0,["expanded"]],[[[1,"            "],[8,[32,3],null,[["@asyncData","@context"],[[30,0,["loadExpandedAcceptedAnswer"]],[30,0,["acceptedAnswer","post_number"]]]],[["content"],[[[[1,"\\n                "],[10,0],[14,0,"expanded-quote"],[15,"data-post-id",[30,1,["id"]]],[12],[1,"\\n                  "],[8,[32,4],null,[["@post","@streamElement"],[[30,1],false]],null],[1,"\\n                "],[13],[1,"\\n              "]],[1]]]]],[1,"\\n"]],[]],[[[1,"            "],[1,[28,[32,5],[[30,0,["acceptedAnswer","excerpt"]]],null]],[1,"\\n"]],[]]],[1,"        "],[13],[1,"\\n"]],[]],null],[1,"    "],[13],[1,"\\n  "]],["expandedAnswer"],false,["unless","if"]]',moduleName:"/var/www/discourse/app/assets/javascripts/discourse/discourse/plugins/discourse-solved/discourse/components/solved-accepted-answer.js",scope:()=>[d.default,o.on,l.default,r.default,a.default,i.htmlSafe],isStrictMode:!0}),this))()}e.default=g})),define("discourse/plugins/discourse-solved/discourse/components/solved-unaccept-answer-button",["exports","@glimmer/component","@ember/object","@ember/service","@ember/template","discourse/components/d-button","discourse/helpers/d-icon","discourse/lib/ajax","discourse/lib/ajax-error","discourse/lib/utilities","discourse-i18n","float-kit/components/d-tooltip","@ember/component","@ember/template-factory"],(function(e,t,s,o,n,c,i,r,a,d,l,u,p,m){"use strict"
Object.defineProperty(e,"__esModule",{value:!0}),e.default=void 0
class v extends t.default{static#e=(()=>dt7948.g(this.prototype,"appEvents",[o.service]))()
#t=(()=>{dt7948.i(this,"appEvents")})()
static#s=(()=>dt7948.g(this.prototype,"siteSettings",[o.service]))()
#i=(()=>{dt7948.i(this,"siteSettings")})()
unacceptAnswer(){const e=this.args.post;(function(e){if(!e.can_unaccept_answer)return
const t=e.topic
e.setProperties({can_accept_answer:!0,can_unaccept_answer:!1,accepted_answer:!1}),t.set("accepted_answer",void 0),(0,r.ajax)("/solution/unaccept",{type:"POST",data:{id:e.id}}).catch(a.popupAjaxError)})(e),this.appEvents.trigger("discourse-solved:solution-toggled",e),e.get("topic.postStream.posts").forEach((e=>{e.set("topic_accepted_answer",!1),this.appEvents.trigger("post-stream:refresh",{id:e.id})}))}static#n=(()=>dt7948.n(this.prototype,"unacceptAnswer",[s.action]))()
get solvedBy(){if(!this.siteSettings.show_who_marked_solved)return
const e=this.args.post.topic.accepted_answer.accepter_username,t=this.args.post.topic.accepted_answer.accepter_name,s=this.siteSettings.display_name_on_posts&&t?t:(0,d.formatUsername)(e)
return this.args.post.topic.accepted_answer.accepter_username?(0,l.i18n)("solved.marked_solved_by",{username:s,username_lower:e}):void 0}static#c=(()=>(0,p.setComponentTemplate)((0,m.createTemplateFactory)({id:"kZOFQn08",block:'[[[1,"\\n    "],[10,1],[14,0,"extra-buttons"],[12],[1,"\\n"],[41,[30,1,["can_unaccept_answer"]],[[[41,[30,0,["solvedBy"]],[[[1,"          "],[8,[32,0],null,[["@identifier"],["post-action-menu__solved-accepted-tooltip"]],[["trigger","content"],[[[[1,"\\n              "],[8,[32,1],[[24,0,"post-action-menu__solved-accepted accepted fade-out"],[17,2]],[["@action","@icon","@label","@title"],[[30,0,["unacceptAnswer"]],"square-check","solved.solution","solved.unaccept_answer"]],null],[1,"\\n            "]],[]],[[[1,"\\n              "],[1,[28,[32,2],[[30,0,["solvedBy"]]],null]],[1,"\\n            "]],[]]]]],[1,"\\n"]],[]],[[[1,"          "],[8,[32,1],[[24,0,"post-action-menu__solved-accepted accepted fade-out"],[17,2]],[["@action","@icon","@label","@title"],[[30,0,["unacceptAnswer"]],"square-check","solved.solution","solved.unaccept_answer"]],null],[1,"\\n"]],[]]]],[]],[[[1,"        "],[10,1],[14,0,"accepted-text"],[15,"title",[28,[32,3],["solved.accepted_description"],null]],[12],[1,"\\n          "],[10,1],[12],[1,[28,[32,4],["check"],null]],[13],[1,"\\n          "],[10,1],[14,0,"accepted-label"],[12],[1,"\\n            "],[1,[28,[32,3],["solved.solution"],null]],[1,"\\n          "],[13],[1,"\\n        "],[13],[1,"\\n"]],[]]],[1,"    "],[13],[1,"\\n  "]],["@post","&attrs"],false,["if"]]',moduleName:"/var/www/discourse/app/assets/javascripts/discourse/discourse/plugins/discourse-solved/discourse/components/solved-unaccept-answer-button.js",scope:()=>[u.default,c.default,n.htmlSafe,l.i18n,i.default],isStrictMode:!0}),this))()}e.default=v})),define("discourse/plugins/discourse-solved/discourse/connectors/after-topic-status/solved-status",["exports","truth-helpers","discourse/helpers/d-icon","discourse-i18n","@ember/component","@ember/template-factory","@ember/component/template-only"],(function(e,t,s,o,n,c,i){"use strict"
Object.defineProperty(e,"__esModule",{value:!0}),e.default=void 0
const r=(0,n.setComponentTemplate)((0,c.createTemplateFactory)({id:"ACmr+cnc",block:'[[[41,[28,[32,0],[[30,1,["topic","has_accepted_answer"]],[30,1,["topic","accepted_answer"]]],null],[[[10,1],[15,"title",[28,[32,1],["topic_statuses.solved.help"],null]],[14,0,"topic-status solved"],[12],[1,[28,[32,2],["far-square-check"],null]],[13]],[]],[[[41,[28,[32,3],[[30,1,["topic","can_have_answer"]],[28,[32,4],[[30,1,["context"]],"topic-list"],null]],null],[[[10,1],[15,"title",[28,[32,1],["solved.has_no_accepted_answer"],null]],[14,0,"topic-status"],[12],[1,[28,[32,2],["far-square"],null]],[13]],[]],null]],[]]]],["@outletArgs"],false,["if"]]',moduleName:"/var/www/discourse/app/assets/javascripts/discourse/discourse/plugins/discourse-solved/discourse/connectors/after-topic-status/solved-status.js",scope:()=>[t.or,o.i18n,s.default,t.and,t.eq],isStrictMode:!0}),(0,i.default)(void 0,"solved-status:SolvedStatus"))
e.default=r})),define("discourse/plugins/discourse-solved/discourse/connectors/bread-crumbs-right/solved-status-filter",["exports","@glimmer/component","@ember/object","@ember/service","discourse-i18n"],(function(e,t,s,o,n){"use strict"
Object.defineProperty(e,"__esModule",{value:!0}),e.default=void 0
const c={solved:"yes",unsolved:"no",all:null},i={yes:"solved",no:"unsolved"}
class r extends t.default{static shouldRender(e,t,s){const o=s.lookup("service:router")
return!(!t.siteSettings.show_filter_by_solved_status||"discovery.categories"===o.currentRouteName||e.editingCategory)&&(!(!t.siteSettings.allow_solved_on_all_topics&&"tag.show"!==o.currentRouteName)||e.currentCategory?.enable_accepted_answers)}static#e=(()=>dt7948.g(this.prototype,"router",[o.service]))()
#u=(()=>{dt7948.i(this,"router")})()
static#s=(()=>dt7948.g(this.prototype,"siteSettings",[o.service]))()
#i=(()=>{dt7948.i(this,"siteSettings")})()
get statuses(){return["all","solved","unsolved"].map((e=>({name:(0,n.i18n)(`solved.topic_status_filter.${e}`),value:e})))}get status(){const e=this.router.currentRoute.queryParams?.solved
return i[e]||"all"}changeStatus(e){this.router.transitionTo({queryParams:{solved:c[e]}})}static#n=(()=>dt7948.n(this.prototype,"changeStatus",[s.action]))()}e.default=r})),define("discourse/plugins/discourse-solved/discourse/connectors/category-custom-settings/solved-settings",["exports"],(function(e){"use strict"
Object.defineProperty(e,"__esModule",{value:!0}),e.default=void 0
e.default={actions:{onChangeSetting(e){this.set("category.custom_fields.enable_accepted_answers",e?"true":"false")}}}})),define("discourse/plugins/discourse-solved/discourse/connectors/topic-navigation/no-answer",["exports","@ember/runloop","discourse/lib/environment"],(function(e,t,s){"use strict"
Object.defineProperty(e,"__esModule",{value:!0}),e.default=void 0
const o=6048e5,n=o,c=(0,s.isTesting)()?0:2e3
e.default={shouldRender:(e,t)=>!t.site.mobileView,setupComponent(e,s){s.set("show",!1),s.setProperties({oneWeek:o,show:!1}),(0,t.later)((()=>{if(!s.element||s.isDestroying||s.isDestroyed)return
const t=e.topic,o=s.currentUser
!t.accepted_answer&&o&&t.user_id===o.id&&moment()-moment(t.created_at)>n&&t.postStream.posts.some((e=>e.user_id!==o.id&&e.can_accept_answer))&&s.set("show",!0)}),c)}}})),define("discourse/plugins/discourse-solved/discourse/connectors/user-activity-bottom/solved-list",["exports","@glimmer/component","@ember/service"],(function(e,t,s){"use strict"
Object.defineProperty(e,"__esModule",{value:!0}),e.default=void 0
class o extends t.default{static#e=(()=>dt7948.g(this.prototype,"siteSettings",[s.service]))()
#i=(()=>{dt7948.i(this,"siteSettings")})()}e.default=o})),define("discourse/plugins/discourse-solved/discourse/connectors/user-summary-stat/solved-count",["exports","@glimmer/component","@ember/service"],(function(e,t,s){"use strict"
Object.defineProperty(e,"__esModule",{value:!0}),e.default=void 0
class o extends t.default{static#e=(()=>dt7948.g(this.prototype,"siteSettings",[s.service]))()
#i=(()=>{dt7948.i(this,"siteSettings")})()}e.default=o})),define("discourse/plugins/discourse-solved/discourse/initializers/add-topic-list-class",["exports","discourse/lib/plugin-api"],(function(e,t){"use strict"
Object.defineProperty(e,"__esModule",{value:!0}),e.default=void 0
e.default={name:"add-topic-list-class",initialize(){(0,t.withPluginApi)("1.39.0",(e=>{e.registerValueTransformer("topic-list-item-class",(e=>{let{value:t,context:s}=e
return s.topic.get("has_accepted_answer")&&t.push("status-solved"),t}))}))}}})),define("discourse/plugins/discourse-solved/discourse/initializers/extend-for-solved-button",["exports","@glimmer/component","discourse/lib/deprecated","discourse/lib/plugin-api","discourse/widgets/render-glimmer","discourse-i18n","discourse/plugins/discourse-solved/discourse/components/solved-accept-answer-button","discourse/plugins/discourse-solved/discourse/components/solved-accepted-answer","discourse/plugins/discourse-solved/discourse/components/solved-unaccept-answer-button","@ember/component","@ember/template-factory","@ember/component/template-only"],(function(e,t,s,o,n,c,i,r,a,d,l,u){"use strict"
function p(e){(function(e){e.addTrackedPostProperties("can_accept_answer","can_unaccept_answer","accepted_answer","topic_accepted_answer"),e.renderAfterWrapperOutlet("post-content-cooked-html",class extends t.default{static shouldRender(e){return 1===e.post.post_number&&e.post.topic.accepted_answer}static#e=(()=>(0,d.setComponentTemplate)((0,l.createTemplateFactory)({id:"Ib9Mvi43",block:'[[[8,[32,0],null,[["@post"],[[30,1,["post"]]]],null]],["@outletArgs"],false,[]]',moduleName:"/var/www/discourse/app/assets/javascripts/discourse/discourse/plugins/discourse-solved/discourse/initializers/extend-for-solved-button.js",scope:()=>[r.default],isStrictMode:!0}),this))()}),(0,s.withSilencedDeprecations)("discourse.post-stream-widget-overrides",(()=>function(e){e.decorateWidget("post-contents:after-cooked",(e=>{let t=e.getModel()
if(1===e.attrs.post_number&&t?.topic?.accepted_answer)return new n.default(e.widget,"div",(0,d.setComponentTemplate)((0,l.createTemplateFactory)({id:"rLkv9tlc",block:'[[[8,[32,0],null,[["@post"],[[30,1,["post"]]]],null]],["@data"],false,[]]',moduleName:"/var/www/discourse/app/assets/javascripts/discourse/discourse/plugins/discourse-solved/discourse/initializers/extend-for-solved-button.js",scope:()=>[r.default],isStrictMode:!0}),(0,u.default)(void 0,void 0)),{post:t})}))}(e)))})(e),function(e){e.registerValueTransformer("post-menu-buttons",(e=>{let t,{value:s,context:{post:o,firstButtonKey:n,secondLastHiddenButtonKey:c,lastHiddenButtonKey:r}}=e
o.can_accept_answer?t=i.default:o.accepted_answer&&(t=a.default),t&&s.add("solved",t,o.topic_accepted_answer&&!o.accepted_answer?{before:r,after:c}:{before:["assign",n]})}))}(e),e.addDiscoveryQueryParam&&e.addDiscoveryQueryParam("solved",{replace:!0,refreshModel:!0})}Object.defineProperty(e,"__esModule",{value:!0}),e.default=void 0
e.default={name:"extend-for-solved-button",initialize(){(0,o.withPluginApi)("1.34.0",p),(0,o.withPluginApi)("0.8.10",(e=>{e.replaceIcon("notification.solved.accepted_notification","square-check")})),(0,o.withPluginApi)("0.11.0",(e=>{e.addAdvancedSearchOptions({statusOptions:[{name:(0,c.i18n)("search.advanced.statuses.solved"),value:"solved"},{name:(0,c.i18n)("search.advanced.statuses.unsolved"),value:"unsolved"}]})})),(0,o.withPluginApi)("0.11.7",(e=>{e.addSearchSuggestion("status:solved"),e.addSearchSuggestion("status:unsolved")}))}}})),define("discourse/plugins/discourse-solved/discourse/pre-initializers/extend-category-for-solved",["exports","@ember/object","discourse/models/category"],(function(e,t,s){"use strict"
Object.defineProperty(e,"__esModule",{value:!0}),e.default=void 0
e.default={name:"extend-category-for-solved",before:"inject-discourse-objects",initialize(){s.default.reopen({enable_accepted_answers:(0,t.computed)("custom_fields.enable_accepted_answers",{get(e){return"true"===(0,t.get)(this.custom_fields,e)}})})}}})),define("discourse/plugins/discourse-solved/discourse/routes/user-activity-solved",["exports","discourse/routes/user-activity-stream","discourse-i18n"],(function(e,t,s){"use strict"
Object.defineProperty(e,"__esModule",{value:!0}),e.default=void 0
class o extends t.default{userActionType=15
noContentHelpKey="solved.no_solutions"
emptyState(){const e=this.modelFor("user")
let t,o
return this.isCurrentUser(e)?(t=(0,s.i18n)("solved.no_solved_topics_title"),o=(0,s.i18n)("solved.no_solved_topics_body")):(t=(0,s.i18n)("solved.no_solved_topics_title_others",{username:e.username}),o=""),{title:t,body:o}}}e.default=o})),define("discourse/plugins/discourse-solved/discourse/solved-route-map",["exports"],(function(e){"use strict"
Object.defineProperty(e,"__esModule",{value:!0}),e.default=void 0
e.default={resource:"user.userActivity",map(){this.route("solved")}}})),define("discourse/plugins/discourse-solved/discourse/templates/connectors/bread-crumbs-right/solved-status-filter",["exports","@ember/template-factory"],(function(e,t){"use strict"
Object.defineProperty(e,"__esModule",{value:!0}),e.default=void 0
e.default=(0,t.createTemplateFactory)({id:"EWhgyyZc",block:'[[[41,[30,0,["siteSettings","solved_enabled"]],[[[1,"  "],[10,"li"],[12],[1,"\\n    "],[8,[39,2],[[24,0,"solved-status-filter"]],[["@content","@value","@valueProperty","@options","@onChange"],[[30,0,["statuses"]],[30,0,["status"]],"value",[28,[37,3],null,[["caretDownIcon","caretUpIcon"],["caret-right","caret-down"]]],[30,0,["changeStatus"]]]],null],[1,"\\n  "],[13],[1,"\\n"]],[]],null]],[],false,["if","li","combo-box","hash"]]',moduleName:"discourse/plugins/discourse-solved/discourse/templates/connectors/bread-crumbs-right/solved-status-filter.hbs",isStrictMode:!1})})),define("discourse/plugins/discourse-solved/discourse/templates/connectors/category-custom-settings/solved-settings",["exports","@ember/template-factory"],(function(e,t){"use strict"
Object.defineProperty(e,"__esModule",{value:!0}),e.default=void 0
e.default=(0,t.createTemplateFactory)({id:"HHV4G+up",block:'[[[10,"h3"],[12],[1,[28,[35,1],["solved.title"],null]],[13],[1,"\\n\\n"],[41,[51,[30,0,["siteSettings","allow_solved_on_all_topics"]]],[[[1,"  "],[10,"section"],[14,0,"field"],[12],[1,"\\n    "],[10,0],[14,0,"enable-accepted-answer"],[12],[1,"\\n      "],[10,"label"],[14,0,"checkbox-label"],[12],[1,"\\n        "],[11,"input"],[16,"checked",[30,0,["category","enable_accepted_answers"]]],[24,4,"checkbox"],[4,[38,7],["change",[28,[37,8],[[30,0],"onChangeSetting"],[["value"],["target.checked"]]]],null],[12],[13],[1,"\\n        "],[1,[28,[35,1],["solved.allow_accepted_answers"],null]],[1,"\\n      "],[13],[1,"\\n    "],[13],[1,"\\n  "],[13],[1,"\\n"]],[]],null],[1,"\\n"],[10,"section"],[14,0,"field auto-close-solved-topics"],[12],[1,"\\n  "],[10,"label"],[14,"for","auto-close-solved-topics"],[12],[1,"\\n    "],[1,[28,[35,1],["solved.solved_topics_auto_close_hours"],null]],[1,"\\n  "],[13],[1,"\\n  "],[11,"input"],[16,2,[30,0,["category","custom_fields","solved_topics_auto_close_hours"]]],[24,"min","0"],[24,1,"auto-close-solved-topics"],[24,4,"number"],[4,[38,7],["input",[28,[37,8],[[30,0],[28,[37,9],[[30,0,["category","custom_fields","solved_topics_auto_close_hours"]]],null]],[["value"],["target.value"]]]],null],[12],[13],[1,"\\n"],[13]],[],false,["h3","i18n","unless","section","div","label","input","on","action","mut"]]',moduleName:"discourse/plugins/discourse-solved/discourse/templates/connectors/category-custom-settings/solved-settings.hbs",isStrictMode:!1})})),define("discourse/plugins/discourse-solved/discourse/templates/connectors/topic-after-cooked/solved-panel",["exports","@ember/template-factory"],(function(e,t){"use strict"
Object.defineProperty(e,"__esModule",{value:!0}),e.default=void 0
e.default=(0,t.createTemplateFactory)({id:"SIlGVU5R",block:'[[[41,[30,0,["topic","accepted_answer"]],[[[1,"  "],[10,2],[14,0,"solved"],[12],[1,"\\n    "],[1,[28,[35,2],[[30,0,["topic","acceptedAnswerHtml"]]],null]],[1,"\\n  "],[13],[1,"\\n"]],[]],null]],[],false,["if","p","html-safe"]]',moduleName:"discourse/plugins/discourse-solved/discourse/templates/connectors/topic-after-cooked/solved-panel.hbs",isStrictMode:!1})})),define("discourse/plugins/discourse-solved/discourse/templates/connectors/topic-navigation/no-answer",["exports","@ember/template-factory"],(function(e,t){"use strict"
Object.defineProperty(e,"__esModule",{value:!0}),e.default=void 0
e.default=(0,t.createTemplateFactory)({id:"gTxERl2N",block:'[[[41,[30,0,["show"]],[[[1,"  "],[8,[39,1],null,[["@popupId","@dismissDuration"],["solved-notice",[30,0,["oneWeek"]]]],[["default"],[[[[1,"\\n    "],[10,"h3"],[12],[1,[28,[35,3],["solved.no_answer.title"],null]],[13],[1,"\\n    "],[10,2],[12],[1,[28,[35,3],["solved.no_answer.description"],null]],[13],[1,"\\n  "]],[]]]]],[1,"\\n"]],[]],null]],[],false,["if","topic-navigation-popup","h3","i18n","p"]]',moduleName:"discourse/plugins/discourse-solved/discourse/templates/connectors/topic-navigation/no-answer.hbs",isStrictMode:!1})})),define("discourse/plugins/discourse-solved/discourse/templates/connectors/user-activity-bottom/solved-list",["exports","@ember/template-factory"],(function(e,t){"use strict"
Object.defineProperty(e,"__esModule",{value:!0}),e.default=void 0
e.default=(0,t.createTemplateFactory)({id:"SwVKLYR2",block:'[[[41,[30,0,["siteSettings","solved_enabled"]],[[[1,"  "],[10,"li"],[14,0,"user-activity-bottom-outlet solved-list"],[12],[1,"\\n    "],[8,[39,2],null,[["@route"],["userActivity.solved"]],[["default"],[[[[1,"\\n      "],[1,[28,[35,3],["square-check"],null]],[1,"\\n      "],[1,[28,[35,4],["solved.title"],null]],[1,"\\n    "]],[]]]]],[1,"\\n  "],[13],[1,"\\n"]],[]],null]],[],false,["if","li","link-to","d-icon","i18n"]]',moduleName:"discourse/plugins/discourse-solved/discourse/templates/connectors/user-activity-bottom/solved-list.hbs",isStrictMode:!1})})),define("discourse/plugins/discourse-solved/discourse/templates/connectors/user-card-metadata/accepted-answers",["exports","@ember/template-factory"],(function(e,t){"use strict"
Object.defineProperty(e,"__esModule",{value:!0}),e.default=void 0
e.default=(0,t.createTemplateFactory)({id:"YgEBzTE2",block:'[[[41,[30,0,["user","accepted_answers"]],[[[1,"  "],[10,1],[14,0,"desc"],[12],[1,[28,[35,2],["solutions"],null]],[13],[1,"\\n  "],[10,1],[12],[1,[30,0,["user","accepted_answers"]]],[13],[1,"\\n"]],[]],null]],[],false,["if","span","i18n"]]',moduleName:"discourse/plugins/discourse-solved/discourse/templates/connectors/user-card-metadata/accepted-answers.hbs",isStrictMode:!1})})),define("discourse/plugins/discourse-solved/discourse/templates/connectors/user-summary-stat/solved-count",["exports","@ember/template-factory"],(function(e,t){"use strict"
Object.defineProperty(e,"__esModule",{value:!0}),e.default=void 0
e.default=(0,t.createTemplateFactory)({id:"2CIaSQ60",block:'[[[41,[28,[37,1],[[30,0,["siteSettings","solved_enabled"]],[30,1,["model","solved_count"]]],null],[[[1,"  "],[10,"li"],[14,0,"user-summary-stat-outlet solved-count linked-stat"],[12],[1,"\\n    "],[8,[39,3],null,[["@route"],["userActivity.solved"]],[["default"],[[[[1,"\\n      "],[8,[39,4],null,[["@value","@label","@icon"],[[30,1,["model","solved_count"]],"solved.solution_summary","square-check"]],null],[1,"\\n    "]],[]]]]],[1,"\\n  "],[13],[1,"\\n"]],[]],null]],["@outletArgs"],false,["if","and","li","link-to","user-stat"]]',moduleName:"discourse/plugins/discourse-solved/discourse/templates/connectors/user-summary-stat/solved-count.hbs",isStrictMode:!1})}))

//# sourceMappingURL=discourse-solved-6af3792d.map